### ISSUE TITLE
Adding Kevin Wurster as an owner

### ISSUE THREAD

**Issue by sgillies** [Toblerity/org#2]
This is so @geowurster can transfer his fio-buffer plugin (https://github.com/Toblerity/Fiona/pull/225#issuecomment-134804336).

Any objections, @Toblerity/owners? I think I got a thumbs up from @hobu already.

**Comment by sgillies** [comment]
You're on, @geowurster.

**Comment by geowurster** [comment]
@sgillies Thanks!  Shall I add a CoC doc as well like https://github.com/Toblerity/Fiona/issues/282?

**Comment by sgillies** [comment]
Yes, please. How about the Contributor Covenant, like in Rasterio?

**Comment by geowurster** [comment]
:+1:
