### ISSUE TITLE
Requiring 2FA for org members with admin privileges

### ISSUE THREAD

**Issue by sgillies** [Toblerity/org#3]
I'd like to require our admins members to turn on 2FA. Objections @Toblerity/owners? Okay if I remove your owner roles until you turn 2FA on?

**Comment by dokai** [comment]
+1, I already have 2FA enabled.

**Comment by olt** [comment]
Yes, go ahead.

**Comment by sgillies** [comment]
@brentp I temporarily demoted you from Owner to Member until you get 2FA.

**Comment by brentp** [comment]
no problem. I likely won't need to access Toblerity anyway.
